name: Deploy Demo
on:
  push:
    branches: [ release/demo-app ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-native.yml
      
  deploy:
    needs: build
    runs-on: macos-aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@v3              
      
      - name: Download native artifacts
        uses: actions/download-artifact@v3
        with:
          name: native-images
          path: ./sample-cli/target/image

      - name: Build Site
        run: conveyor make copied-site

      - name: Upload Site
        uses: actions/upload-artifact@v3
        with:
          name: conveyor-site
          path: ./output/**
          retention-days: 10
