name: Maven Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  native-image:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-13, macos-14] # macos13 is Intel, 14 is Arm
    
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/checkout@v3
    - uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.1

    - name: 'Install Linux dependencies for JavaFX'
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update && sudo apt-get install -y libxtst-dev libharfbuzz-dev libgtk-3-dev libgdk-pixbuf2.0-dev libpango1.0-dev libcairo2-dev libatk1.0-dev libgl1-mesa-dev zlib1g-dev
        
    - uses: graalvm/setup-graalvm@v1
      with:
        distribution: 'liberica'
        java-package: 'jdk+fx'
        java-version: '21'
        set-java-home: 'true'
        native-image-job-reports: 'true'
        cache: 'maven'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Show versions
      run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
          
    - name: Build native image and launchers
      run: mvn clean package -Pnative
